### ISSUE TITLE
接口是不是挂了大佬

### ISSUE THREAD

**Issue by ddy4633** [xshen1898/StockMonitoring#1]
stock-limit-up.py  有时间更新一波吧

**Comment by ddy4633** [comment]
Traceback (most recent call last):
  File "stock-limit-up.py", line 25, in <module>
    stock_data = get_data()
  File "stock-limit-up.py", line 20, in get_data
    data_dict = json.loads(data_str)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by xshen1898** [comment]
Updated. If you like, please give it a star. Thanks.
